#Analisi del dataset fumetti DC

In [1]:
from pathlib import Path

import pandas as pd

BASE_PATH = Path('/Users/marcogreco/ComicGraph')
DATASET_PATH = BASE_PATH / 'Dataset' / 'Dataset_Originali'

MARVEL_COMICS_PATH = DATASET_PATH / 'Marvel_Comics.csv'
DC_COMICS_PATH = DATASET_PATH / 'DC_Comics.csv'

In [2]:
# Caricamento del dataset DC Comics
DC_COMICS = pd.read_csv(DC_COMICS_PATH)

print('Numero di righe:', len(DC_COMICS))
print('Numero di colonne:', len(DC_COMICS.columns))
print('Colonne del dataset:')
print(DC_COMICS.columns.tolist())

Numero di righe: 53398
Numero di colonne: 15
Colonne del dataset:
['Catergory_Title', 'Issue_Name', 'Issue_Link', 'Pencilers', 'Cover_Artists', 'Inkers', 'Writers', 'Editors', 'Executive_Editor', 'Letterers', 'Colourists', 'Rating', 'Release_Date', 'Comic_Series', 'Comic_Type']

In [4]:
# Analisi dei valori mancanti per colonna
missing_dc = (
    DC_COMICS.isna()
    .sum()
    .rename('valori_mancanti')
    .to_frame()
)

missing_dc['percentuale'] = (
    missing_dc['valori_mancanti'] / len(DC_COMICS) * 100
).round(2)

missing_dc.sort_values(
    'valori_mancanti',
    ascending=False
)

                  valori_mancanti  percentuale
Rating                      41389        77.51
Colourists                  19238        36.03
Letterers                   17560        32.89
Executive_Editor            16351        30.62
Editors                      8894        16.66
Writers                      5569        10.43
Inkers                       3764         7.05
Cover_Artists                2975         5.57
Pencilers                    2910         5.45
Release_Date                  443         0.83
Catergory_Title                 0         0.00
Issue_Name                      0         0.00
Issue_Link                      0         0.00
Comic_Series                    0         0.00
Comic_Type                      0         0.00

In [3]:
# Analisi dei duplicati completi nel dataset DC
DC_DUPLICATES = DC_COMICS[DC_COMICS.duplicated(keep=False)].copy()

print('Duplicati completi DC:', DC_COMICS.duplicated().sum())
print('Righe coinvolte nei duplicati DC:', len(DC_DUPLICATES))

DC_DUPLICATES.head()

Duplicati completi DC: 216
Righe coinvolte nei duplicati DC: 365

,Catergory_Title,Issue_Name,Issue_Link,Pencilers,Cover_Artists,Inkers,Writers,Editors,Executive_Editor,Letterers,Colourists,Rating,Release_Date,Comic_Series,Comic_Type
271,Justice League United Vol 1,2014,https://dc.fandom.com/wiki/2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014,Adam Strange Titles,Category
273,Justice League United Vol 1,2014,https://dc.fandom.com/wiki/2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014,Adam Strange Titles,Category
564,Strange Adventures Vol 1,Strange Adventures #50,https://dc.fandom.com/wiki/Strange_Adventures_...,Carmine Infantino,Murphy Anderson,Carmine Infantino,Otto Binder,Julius Schwartz,Whitney Ellsworth,NaN,NaN,NaN,"November, 1954",Adam Strange Titles,Category
565,Strange Adventures Vol 1,Strange Adventures #50,https://dc.fandom.com/wiki/Strange_Adventures_...,Carmine Infantino,Murphy Anderson,Carmine Infantino,Otto Binder,Julius Schwartz,Whitney Ellsworth,NaN,NaN,NaN,"November, 1954",Adam Strange Titles,Category
1187,Justice League United Vol 1,2014,https://dc.fandom.com/wiki/2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014,Animal Man Titles,Category

In [4]:
# Caricamento e analisi dei duplicati completi nel dataset Marvel
MARVEL_COMICS = pd.read_csv(MARVEL_COMICS_PATH)
MARVEL_DUPLICATES = MARVEL_COMICS[MARVEL_COMICS.duplicated(keep=False)].copy()

print('Duplicati completi Marvel:', MARVEL_COMICS.duplicated().sum())
print('Righe coinvolte nei duplicati Marvel:', len(MARVEL_DUPLICATES))

MARVEL_DUPLICATES.head()

Duplicati completi Marvel: 139
Righe coinvolte nei duplicati Marvel: 277

,comic_name,active_years,issue_title,publish_date,issue_description,penciler,writer,cover_artist,Imprint,Format,Rating,Price
249,Agent Carter: S.H.I.E.L.D. 50th Anniversary (2...,(2015),Agent Carter: S.H.I.E.L.D. 50th Anniversary (2...,"September 16, 2015",Agent Carter is back in an all-new adventure t...,Declan Shalvey,Kathryn Immonen,NaN,Marvel Universe,Comic,NaN,$3.99
250,Agent Carter: S.H.I.E.L.D. 50th Anniversary (2...,(2015),Agent Carter: S.H.I.E.L.D. 50th Anniversary (2...,"September 16, 2015",Agent Carter is back in an all-new adventure t...,Declan Shalvey,Kathryn Immonen,NaN,Marvel Universe,Comic,NaN,$3.99
2814,Avengers: Earth's Mightiest Heroes II (2006 - ...,(2006 - 2007),Avengers: Earth's Mightiest Heroes II (2006) #8,"April 18, 2007",This is it! The concluding chapter of this unt...,William Rosado,Joe Casey,Dave Johnson,MARVEL UNIVERSE,Comic,A,$3.99
2815,Avengers: Earth's Mightiest Heroes II (2006 - ...,(2006 - 2007),Avengers: Earth's Mightiest Heroes II (2006) #8,"April 18, 2007",This is it! The concluding chapter of this unt...,William Rosado,Joe Casey,Dave Johnson,MARVEL UNIVERSE,Comic,A,$3.99
5697,Criminal: The Last of the Innocent (2011),(2011),Criminal: The Last of the Innocent (2011) #1,"June 01, 2011","The best-selling crime comic finally returns, ...",Sean Phillips,Ed Brubaker,Sean Phillips,NaN,Comic,NaN,$3.50

In [6]:
# Analisi delle stringhe speciali Not Available
special_value = 'Not Available'

special_values_report = []
for brand, dataframe in [('DC', DC_COMICS), ('Marvel', MARVEL_COMICS)]:
    matches_by_column = (dataframe == special_value).sum()
    for column, count in matches_by_column[matches_by_column > 0].items():
        special_values_report.append({
            'dataset': brand,
            'colonna': column,
            'valore': special_value,
            'occorrenze': int(count),
        })

special_values_report = pd.DataFrame(special_values_report)

if special_values_report.empty:
    print('La stringa Not Available non è presente nei due dataset.')
else:
    print(special_values_report.to_string(index=False))

dataset    colonna        valore  occorrenze
     DC Issue_Name Not Available         377
     DC Issue_Link Not Available         377